// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DebugController from "./debug_controller"
application.register("debug", DebugController)

import MapseditController from "./mapsedit_controller"
application.register("mapsedit", MapseditController)

import PropertyformController from "./propertyform_controller"
application.register("propertyform", PropertyformController)

import RdashboardController from "./rdashboard_controller"
application.register("rdashboard", RdashboardController)

import ReactclientindexController from "./reactclientindex_controller"
application.register("reactclientindex", ReactclientindexController)

import ReacteditmapController from "./reacteditmap_controller"
application.register("reacteditmap", ReacteditmapController)

import ReactjobindexController from "./reactjobindex_controller"
application.register("reactjobindex", ReactjobindexController)

import ReactjobshowController from "./reactjobshow_controller"
application.register("reactjobshow", ReactjobshowController)

import ReactnewjobController from "./reactnewjob_controller"
application.register("reactnewjob", ReactnewjobController)

import ReactpropshowController from "./reactpropshow_controller"
application.register("reactpropshow", ReactpropshowController)

import RfleetController from "./rfleet_controller"
application.register("rfleet", RfleetController)

import RprofileController from "./rprofile_controller"
application.register("rprofile", RprofileController)
