// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import DashjobsmapController from "./dashjobsmap_controller"
application.register("dashjobsmap", DashjobsmapController)

import DebugController from "./debug_controller"
application.register("debug", DebugController)

import JobformController from "./jobform_controller"
application.register("jobform", JobformController)

import JobshowController from "./jobshow_controller"
application.register("jobshow", JobshowController)

import MapseditController from "./mapsedit_controller"
application.register("mapsedit", MapseditController)

import PropertyformController from "./propertyform_controller"
application.register("propertyform", PropertyformController)

import RdashboardController from "./rdashboard_controller"
application.register("rdashboard", RdashboardController)

import ReactnewjobController from "./reactnewjob_controller"
application.register("reactnewjob", ReactnewjobController)

import ReactpropshowController from "./reactpropshow_controller"
application.register("reactpropshow", ReactpropshowController)

import UserprofileController from "./userprofile_controller"
application.register("userprofile", UserprofileController)
